steps:
  # Step 1: Lint Python code
  - name: python:3.14
    id: lint-python
    entrypoint: bash
    args:
      - -c
      - |
        echo "Installing lint tools..."
        python -m venv .venv && source .venv/bin/activate
        pip install flake8 black isort pylint pytest pytest-cov -q

        echo "Running flake8..."
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true

        echo "Checking black formatting..."
        black --check . || true

        echo "Checking import sorting..."
        isort --check-only . || true

        echo "Running pylint..."
        pylint app/ --fail-under=7.0 --exit-zero || true

  # Step 2: Run unit tests with coverage
  - name: python:3.14
    id: test-python
    entrypoint: bash
    args:
      - -c
      - |
        echo "Installing dependencies..."
        python -m venv .venv && source .venv/bin/activate
        pip install -r requirements.txt -r requirements-dev.txt -q

        echo "Running pytest with coverage..."
        pytest tests/ \
          --cov=app \
          --cov-report=term-missing \
          --cov-report=xml \
          --junitxml=test-results.xml || true

        echo "Test results generated"

  # Step 3: Lint Terraform
  - name: "hashicorp/terraform:1.10"
    id: lint-terraform
    entrypoint: sh
    args:
      - -c
      - |
        set -e
        cd terraform

        echo "Initializing Terraform..."
        terraform init -backend=false -upgrade

        echo "Running terraform fmt check..."
        if ! terraform fmt -check -recursive .; then
          echo "Formatting issues found. Run 'terraform fmt -recursive' locally."
          exit 1
        fi

        echo "Running terraform validate..."
        terraform validate

        echo "All Terraform lint checks passed"

  # Step 4: Build Docker image
  - name: gcr.io/cloud-builders/docker
    id: build-docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:latest
      - -f
      - Dockerfile
      - .

  # Step 5: Push to Artifact Registry (short SHA & latest tag)
  - name: gcr.io/cloud-builders/docker
    id: push-docker-sha
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}

  # Step 7: Scan Docker image for vulnerabilities (Trivy)
  - name: aquasec/trivy
    id: scan-image
    args:
      - image
      - --exit-code=0
      - --severity=HIGH,CRITICAL
      - --no-progress
      - --format=json
      - --output=trivy-results.json
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}

  # Step 8: Deploy via Terraform
  - name: "hashicorp/terraform:1.10"
    id: deploy-terraform
    entrypoint: sh
    args:
      - -c
      - |
        cd terraform

        echo "Initializing Terraform..."
        terraform init \
          -backend-config="bucket=${_TERRAFORM_STATE_BUCKET}" \
          -backend-config="prefix=terraform/state" \
          -upgrade

        echo "Planning Terraform changes..."
        terraform plan \
          -var="image_tag=${SHORT_SHA}" \
          -out=tfplan

        echo "Applying Terraform changes..."
        terraform apply \
          -auto-approve \
          tfplan

        echo "Deployment complete!"
        terraform output deployment_summary

  # Step 9: Output deployment info
  - name: gcr.io/cloud-builders/gcloud
    id: output-info
    entrypoint: bash
    args:
      - -c
      - |
        echo "=== Deployment Summary ==="
        echo "Project: ${PROJECT_ID}"
        echo "Region: ${_REGION}"
        echo "Service: ${_SERVICE_NAME}"
        echo "Image Tag: ${SHORT_SHA}"
        echo "Repository: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE_NAME}"

# Build configuration
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

# Images to be pushed
images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE_NAME}:latest
# Artifacts to store
artifacts:
  objects:
    location: gs://${_ARTIFACT_BUCKET}/${BUILD_ID}
    paths:
      - test-results.xml
      - trivy-results.json

# Substitutions
substitutions:
  _REGION: africa-south1
  _REPO: insight-agent-artifact-repo
  _SERVICE_NAME: insight-agent
  _IMAGE_NAME: insight-agent
  _TERRAFORM_DEPLOYER_SA: cloudrun-deployer@${PROJECT_ID}.iam.gserviceaccount.com
  _ARTIFACT_BUCKET: ${PROJECT_ID}-build-artifacts
  _TERRAFORM_STATE_BUCKET: insight-agent-pawait-tf-state

# Build timeout
timeout: 1800s

# Required Python files
tags:
  - gcp-cloud
  - insight-agent
  - python
  - terraform
