project_id                = "insight-agent-pawait"
project_name              = "Insight Agent"
region                    = "africa-south1"
zone                      = "africa-south1-a"
artifact_repo_id          = "insight-agent-artifact-repo"
artifact_repo_description = "Artifact repository for Insight Agent"
image_tag                = "latest"
service_account_email     = "cloudrun-runtime@insight-agent-pawait.iam.gserviceaccount.com"
cloud_run_service_name    = "insight-agent"
container_port           = 8080
min_instances            = 0
max_instances            = 3
cpu_limit                = "1"
memory_limit             = "512Mi"
cpu_request              = "0.5"
memory_request           = "256Mi"
timeout_seconds          = 300
liveness_probe_path     = "/health"
startup_probe_path      = "/health"
